apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cassandra-master
  name: cassandra-master
spec:
  replicas: 1
  selector:
    app: cassandra-master
    deploymentconfig: cassandra-master
  template:
    metadata:
      labels:
        app: cassandra-master
        deploymentconfig: cassandra-master
    spec:
      containers:
        - image: >-
            cassandra@sha256:f7408a24c1d0d1436c5a0b200b5db777f76f7e0e13b4117547c3686b72483dfc
          imagePullPolicy: Always
          name: cassandra-master
          ports:
            - containerPort: 7000
              protocol: TCP
            - containerPort: 7001
              protocol: TCP
            - containerPort: 7199
              protocol: TCP
            - containerPort: 9042
              protocol: TCP
            - containerPort: 9160
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-master
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: cassandra-master